"""Department service layer and routing context helpers."""

from app.departments.service import (
    DepartmentInUseError,
    activate_department,
    add_department_member,
    build_department_routing_context,
    create_department,
    create_department_knowledge,
    create_raci_assignment,
    deactivate_department,
    delete_department_knowledge,
    delete_department_safely,
    delete_raci_assignment,
    get_department,
    list_department_knowledge,
    list_department_members,
    list_departments,
    list_raci_assignments,
    remove_department_member,
    set_department_active,
    set_department_knowledge_active,
    update_department,
    update_department_knowledge,
    update_department_member,
    update_raci_assignment,
)

__all__ = [
    "DepartmentInUseError",
    "activate_department",
    "add_department_member",
    "build_department_routing_context",
    "create_department",
    "create_department_knowledge",
    "create_raci_assignment",
    "deactivate_department",
    "delete_department_knowledge",
    "delete_department_safely",
    "delete_raci_assignment",
    "get_department",
    "list_department_knowledge",
    "list_department_members",
    "list_departments",
    "list_raci_assignments",
    "remove_department_member",
    "set_department_active",
    "set_department_knowledge_active",
    "update_department",
    "update_department_knowledge",
    "update_department_member",
    "update_raci_assignment",
]
